ARG HOST

FROM php:7.4-apache
ARG GIT_REF
ARG VERSION

RUN echo "GIT_REF is ${GIT_REF}"
RUN curl -o /master.zip -L https://github.com/the-djmaze/snappymail/archive/refs/${GIT_REF}.zip

COPY ./snappymail.conf /etc/apache2/sites-available/snappymail.conf
COPY ./mail.example.com.pem /etc/certs/mail.example.com.pem

RUN apt-get update && apt-get install -y unzip && unzip -o /master.zip -d /tmp/x1 && \
	mkdir /var/www/snappymail && \
	mv /tmp/x1/*/* /var/www/snappymail && \
	mv /tmp/x1/*/.* /var/www/snappymail || true

# Optional: add CSS customizations
# COPY css-customizations/customizations.css  /tmp/customizations.css
# RUN export VERSION=$(cat /version) && ls -R /var/www/snappymail/snappymail/ && cat /tmp/customizations.css >> /var/www/snappymail/snappymail/v/$VERSION/static/css/app.min.css

RUN chown www-data:www-data /var/www/snappymail/ -R

RUN a2ensite snappymail.conf

RUN a2enmod rewrite && \
    a2enmod ssl
WORKDIR /var/www/snappymail
